### ISSUE TITLE
How to fix this? Bot Token invalid

### ISSUE THREAD

**Issue by Vincesq** [ethical-programmer/create-discobase#1]
i put already a token but when I type node . in terminal

PS C:\Users\vinzu\Desktop\Nota> node .
ERROR: The token provided for the Discord bot is invalid. Please check your configuration.
PS C:\Users\vinzu\Desktop\Polly> node .
ERROR: The token provided for the Discord bot is invalid. Please check your configuration.

pls help me solve this I want to create a bot for my own community

**Comment by ethical-programmer** [comment]
Where you provided the token; you should only provide the token in config.json and not anywhere else. If you have only provided it in config.json and are still facing this issue, go to your developer portal, reset the bot's token, and enter the new token. If you still encounter issues, join my Discord server, and we will help you solve it there. 

**[Join Our Discord Server](https://discord.gg/ethical-programmer-s-1188398653530984539)**
